### ISSUE TITLE
Messages are not translated when a book is open

### ISSUE THREAD

**Issue by nvdaes** [readium/readium-desktop#1008] opened 2020-04-15 09:22 UTC
STR:

1. Select a non English language and explore elements.
2. Open a book and explore elements such as settings, navigation, etc.
Expected:
Messages should be translated.

Actual:
When a book is open, messages are shown in English.

**Comment by danielweck** [comment] 2020-04-15 09:31
Oh, that's right! This looks like a regression, @panaC when you have time would you mind taking a look at the Redux store / state synchro with the reader window?

**Comment by danielweck** [comment] 2020-04-15 09:39
The local reader window Redux state is correct (`i18n.locale` is the correct language code) ... so there must be a problem somewhere in the Translator HOC?

**Comment by danielweck** [comment] 2020-04-15 09:47
Ok I found the problem: 
https://github.com/readium/readium-desktop/blob/develop/src/renderer/library/redux/sagas/i18n.ts
...absent in reader:
https://github.com/readium/readium-desktop/tree/develop/src/renderer/reader/redux/sagas

**Comment by danielweck** [comment] 2020-04-15 09:52
@panaC I am fixing this...

**Comment by danielweck** [comment] 2020-04-15 09:56
Fixed via: https://github.com/readium/readium-desktop/commit/a38d3e12bbf20379d022cff838de9eb07bef65dc

**Closed** 2020-04-15 09:56 UTC
