### ISSUE TITLE
OPDS catalogs: cannot past a URL anymore 

### ISSUE THREAD

**Issue by llemeurfr** [readium/readium-desktop#412] opened 2019-07-11 14:06 UTC
Just copy a URL somewhere and try pasting in in the text field. Impossible

**Comment by panaC** [comment] 2019-07-11 15:05
related to #390

**Comment by danielweck** [comment] 2019-07-11 17:21
Pierre is right, duplicate of https://github.com/readium/readium-desktop/issues/390

**Closed by danielweck** 2019-07-11 17:21 UTC
Labels: bug
