### ISSUE TITLE
crash catalog view with an opds feed

### ISSUE THREAD

**Issue by panaC** [readium/readium-desktop#808] opened 2019-10-22 13:41 UTC
opds : [http://manybooks.net/opds/](http://manybooks.net/opds/)

```
readium-desktop:main/converter/opds getSearchUrlFromOpds1Feed TypeError: Cannot read property 'Url' of undefined
[2]     at OpdsFeedViewConverter.<anonymous> (/Users/Pierre/Documents/thorium/dist/main.js:2658:49)
[2]     at Generator.next (<anonymous>)
[2]     at fulfilled (/Users/Pierre/Documents/thorium/node_modules/tslib/tslib.js:107:62)
[2]     at processTicksAndRejections (internal/process/task_queues.js:89:5) +793ms

```

![image](https://user-images.githubusercontent.com/3198865/67290937-15ad2b00-f4e1-11e9-8933-667d31698f24.png)
![image](https://user-images.githubusercontent.com/3198865/67290971-1e056600-f4e1-11e9-930a-8f3f506512ee.png)
click on the first arrow
![image](https://user-images.githubusercontent.com/3198865/67291037-36758080-f4e1-11e9-9653-d09922b7a19a.png)
crash and return to bookshelf

When i return on catalog, it's blocked on manybook/new Titles
and i cannot click on the return arrow

```
eadium-desktop:renderer:bookshelf_ Warning: Hash history cannot PUSH the same path; a new entry will not be added to the history stack +256ms
```

whith the opds1 converter : https://readium2.herokuapp.com/opds-v1-v2-convert/http%3A%2F%2Fmanybooks.net%2Fopds%2Fnew_titles.php

The publication is located in the navigation and not into the publication array.

How to fix thorium for not crash on bad opds feed implementation ?

**Comment by panaC** [comment] 2019-10-27 18:24
I can't reproduce this issue, this is has been probably fixed

Can we close it @danielweck ?

**Comment by danielweck** [comment] 2019-11-13 22:16
I cannot reproduce. Closing.

**Closed by danielweck** 2019-11-13 22:16 UTC
Labels: bug
