### ISSUE TITLE
display settings (in reader view) should behave like language choice and theme selection (radio with single active option)

### ISSUE THREAD

**Issue by danielweck** [readium/readium-desktop#350] opened 2019-06-20 18:09 UTC
Right now, the column etc. preferences are accessible via keyboard tab navigation, instead of arrow key which is standard practice for radio "buttons"

**Comment by danielweck** [comment] 2019-06-22 20:57
Related issue: https://github.com/readium/readium-desktop/issues/303

**Comment by panaC** [comment] 2019-07-03 13:25
related to #365

**Comment by danielweck** [comment] 2019-07-03 14:53
Hello @panaC did you close this issue intentionally? If so, is there a bugfix for it, and could you please link to the corresponding PR? Alternatively, if this is a duplicate, could you please add a message like "closing as duplicate of #xx". Thank you! :)

**Comment by panaC** [comment] 2019-07-03 15:15
Sorry Daniel,

closing as duplicate of #365

**Comment by danielweck** [comment] 2019-07-03 15:17
#365 and #350 are two different problems.

**Comment by danielweck** [comment] 2019-07-09 18:13
Work in Progress in PR: https://github.com/readium/readium-desktop/pull/401

**Closed** 2019-07-19 18:20 UTC
