### ISSUE TITLE
Unable to see full page height on Windows/Linux

### ISSUE THREAD

**Issue by lexterror** [readium/readium-desktop#880] opened 2019-12-09 17:23 UTC
I opened an epub3 fixed-layout ebook with readium-desktop and I can't see the full page no matter what screen size I use.

I have tried on 2560x1080 display and 1920x1080 display and the full page content never displays. It also won't allow me to zoom in or out. I have tried in both Windows and Linux latest version.

I just noticed there's a ~300px "border" right above the pages blocking the full page height.

https://ibb.co/ZfFsx1c

I have the same problem with ALL epub books now.

Thank you.

**Comment by casperkloppenburg** [comment] 2019-12-10 09:22
I got this too with my epub files in paginated mode with version 1.0.6. Version 1.0.5 works fine.

**Comment by danielweck** [comment] 2019-12-12 15:22
Very strange bug, which I am not able to reproduce on MacOS and Windows (I have not tried on Linux, but I will soon)

**Comment by lexterror** [comment] 2019-12-12 15:43
danielweck by any chance do you know where the settings are stored for Thorium on linux?

I'm going to try deleting the settings/folder to see if it fixes the issue.

https://i.imgur.com/jTkfCbA.png

**Comment by danielweck** [comment] 2019-12-12 16:42
I am able to reproduce the bug!!
I am investigating.

**Comment by danielweck** [comment] 2019-12-12 17:45
Fixed via https://github.com/readium/readium-desktop/commit/5c54bfa6156775727691829418fbe2bff36a684e

 Thank you for letting us know!

**Closed** 2019-12-12 17:44 UTC
