### ISSUE TITLE
Themes: the whole reading window should be skined

### ISSUE THREAD

**Issue by llemeurfr** [readium/readium-desktop#295] opened 2019-06-14 11:43 UTC
Currently, the sepia and night themes only change the text of the publication, not the margins, not the app UI. 
It will be a much better experience when we manage to change that.

**Comment by panaC** [comment] 2019-06-29 08:19
related with #83

**Comment by danielweck** [comment] 2019-10-04 14:27
Duplicate of older issue: https://github.com/readium/readium-desktop/issues/83

**Closed by danielweck** 2019-10-04 14:27 UTC
Labels: css, enhancement
