### ISSUE TITLE
Grid view not accessible, would like list view to persist

### ISSUE THREAD

**Issue by GeorgeKerscher** [readium/readium-desktop#968] opened 2020-03-07 23:21 UTC

**Comment by GeorgeKerscher** [comment] 2020-03-07 23:24
When in the library view/bookshelf, the default seems to be the grid view. This says cover for each entry. I select the list view and can walk through the titles in the Bookshelf. However, when I reopen Thorium, it reverts back to grid view. I would like to have the list view to persist, or perhaps a setting that allows the person to select grid view or list view.

**Comment by danielweck** [comment] 2020-03-10 20:43
Hi George, it looks like you closed this issue unintentionally after posting it?

First and foremost, we must ensure that the grid view is accessible. In my tests with VoiceOver, the title and author metadata is announced when browsing the cover images in the library's grid view. Maybe this is a problem with NVDA, let me check on Windows ...

**Comment by danielweck** [comment] 2020-03-10 20:49
I am not able to reproduce this bug on Windows 10 with NVDA either. Could you please confirm whether this problem occurs with the Windows Store version of Thorium, or the more up to date automated build from https://github.com/readium/readium-desktop/releases ?

**Comment by GeorgeKerscher** [comment] 2020-03-10 21:10
Hi,

 

I did not mean to close this item. 

 

I have replicated on both the Microsoft store version and the one with shortcut key modification support.

 

In Grid view, I get cover  image and then a graphic to expand. When expanded I have about, delete, and export. If I activate about, I get what I think is the information about this book.

 

Best

George

**Comment by danielweck** [comment] 2020-03-11 09:32
Hi George, there is definitely an accessible label announcing publication title and authors, when keyboard-tabbing on the cover image link. However, there might also be some confusion because of the screen reader delay between announcing the generic cover image link, and its accessible label, because of nested link image. So, I have fixed that in the latest build, the announcement is now immediate (tested with Voice Over on Mac,  as well as NVDA on Windows).

**Closed** 2020-03-11 09:31 UTC

**Comment by GeorgeKerscher** [comment] 2020-03-11 15:51
Hello,

 

Grid view is working with build 426!!!

 

Best

George
