### ISSUE TITLE
Information button is not functional the first time you read a book

### ISSUE THREAD

**Issue by mutterback** [readium/readium-desktop#433] opened 2019-07-16 03:00 UTC
After adding a new EPUB, open the book in reader view. The first time you are reading the book, if you click on the "i" info button there is no response. The button highlights, but you do not get the information pop up.

Close the book. Open it again. The info button works.

**Comment by panaC** [comment] 2019-07-16 10:31
related to #292 

@danielweck can we close this duplicate ?

**Comment by danielweck** [comment] 2019-07-16 12:13
Duplicate of: https://github.com/readium/readium-desktop/issues/292

**Closed by danielweck** 2019-07-16 12:13 UTC
